theme = "papercolor-dark"

[editor]
true-color = true
cursorline = true
bufferline = "multiple"
color-modes = true
soft-wrap.enable = true
shell = ["fish", "-c"]
auto-save = true
text-width = 80
soft-wrap.wrap-at-text-width = true
# gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
# rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [ "position", "position-percentage", "spacer", "separator", "spacer", "diagnostics","selections", "file-encoding", "file-line-ending"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal]
G = "goto_file_end"
X = "extend_line_above"
C-a = "goto_line_start"
C-e = "goto_line_end"
C-x = ":buffer-close"
y = {y = ["extend_line_below", "yank"]}
# dd = ["extend_line_below", "delete_selection"]
N = ["move_next_long_word_start"]
space = {c = ":theme papercolor-dark"}
C-w = {C-w = ":buffer-next"}
# space = {c = ":config-open"}
C-l = [":new", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme nord", ":theme default"]
# C-f = [":open tempfile.txt", ":insert-output lf-pick", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!"]
# replace the default after theme with the theme you use
# open 1 with the open command (l and <left> to open) or more with (<space> to select) then quit
# all opened files will be opened in helix


[keys.normal.d]
# d = ["extend_line", "delete_selection"]
d = ["extend_to_line_bounds", "delete_selection"]
e = ["kill_to_line_end"]
a = ["kill_to_line_start"]
b = ["delete_word_backward"]
n = ["delete_word_forward"]

[keys.normal.Z]
Z = ":write-quit"
Q = ":quit"

[keys.insert]
# j = { k = "normal_mode" }
C-a = "insert_at_line_start"
C-e = "insert_at_line_end"

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode
j = "normal_mode" # Maps `jk` to exit insert mode

[keys.insert.k]
j = "normal_mode" # Maps `jk` to exit insert mode


[keys.select]
C-a = "goto_line_start"
C-e = "goto_line_end"
# G = "goto_file_end"
